name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  make-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make Cache
        uses: Swatinem/rust-cache@v2.7.3
        with:
          save-if: true
          cache-all-crates: true
          shared-key: tests
      - name: Update Toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update
      - name: Job
        run: cargo build

  Clippy:
    needs: make-cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load Cache
        uses: Swatinem/rust-cache@v2.7.3
        with:
          # save-if: false
          shared-key: tests
          key: clippy
      - name: Update Toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update
      - name: Job
        run: cargo clippy -- -D warnings

  build:
    needs: 
      - Clippy
    runs-on: ubuntu-latest
    env: 
      repo: ${{ github.repository }}
      owner: ${{ github.repository_owner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Convert to lowercase
        id: c2l
        run: | 
          INPUT=${{ env.repo }}; echo "l_repo=${INPUT,,}">>${GITHUB_OUTPUT}
          INPUT=${{ env.owner }}; echo "l_owner=${INPUT,,}">>${GITHUB_OUTPUT}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{steps.c2l.outputs.l_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{steps.c2l.outputs.l_repo}}:latest